### PR TITLE
update tests with TaxoNet as default classifier

### LINKED ISSUE #5: Tests need to be updated wrt TaxoNet and hierarchical taxonomy
See: https://travis-ci.org/github/BirdVox/birdvoxclassify/jobs/729747714

### PR DESCRIPTION
**Pull request by lostanlen**
fixes #5

### CODE REVIEW

**Comment by lostanlen** [comment]
tests are passing locally. this is ready for CR

it might be worth bumping the version number immediately after merging this
(0.1.2)

**Comment by lostanlen** [comment]
tests are passing on py36 but failing on py35
Here's the relevant part of the backtrace


```
Building wheels for collected packages: librosa, resampy, audioread, llvmlite

  Running setup.py bdist_wheel for librosa ... done

  Stored in directory: /home/travis/.cache/pip/wheels/4c/6e/d7/bb93911540d2d1e44d690a1561871e5b6af82b69e80938abef

  Running setup.py bdist_wheel for resampy ... done

  Stored in directory: /home/travis/.cache/pip/wheels/fa/c1/56/e0e12c6f7f3d2cdea9712b35136a2d40a7817c6210ec096485

  Running setup.py bdist_wheel for audioread ... done

  Stored in directory: /home/travis/.cache/pip/wheels/6d/55/fc/0d9cb2a5a52cc24d86cfcd5db4d40f448a43b9a6046c019fc1

  Running setup.py bdist_wheel for llvmlite ... error

  Complete output from command /home/travis/virtualenv/python3.5.6/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-pflm3cvt/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-lu89h0s1 --python-tag cp35:

  running bdist_wheel

  /home/travis/virtualenv/python3.5.6/bin/python /tmp/pip-install-pflm3cvt/llvmlite/ffi/build.py

  LLVM version... # static-libstdc++ avoids runtime dependencies on a

  # particular libstdc++ version.

  g++  -shared   -fPIC -I/usr/local/clang-7.0.0/include -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wcovered-switch-default -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wstring-conversion -ffunction-sections -fdata-sections -O3 -DNDEBUG -fno-exceptions -fno-rtti -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -fno-rtti -g -flto assembly.cpp bitcode.cpp core.cpp initfini.cpp module.cpp value.cpp executionengine.cpp transforms.cpp passmanagers.cpp targets.cpp dylib.cpp linker.cpp object_file.cpp -o libllvmlite.so  -L/usr/local/clang-7.0.0/lib -flto -Wl,--exclude-libs=ALL -lLLVMLTO -lLLVMPasses -lLLVMObjCARCOpts -lLLVMSymbolize -lLLVMDebugInfoPDB -lLLVMDebugInfoDWARF -lLLVMMIRParser -lLLVMFuzzMutate -lLLVMCoverage -lLLVMTableGen -lLLVMDlltoolDriver -lLLVMOrcJIT -lLLVMXCoreDisassembler -lLLVMXCoreCodeGen -lLLVMXCoreDesc -lLLVMXCoreInfo -lLLVMXCoreAsmPrinter -lLLVMSystemZDisassembler -lLLVMSystemZCodeGen -lLLVMSystemZAsmParser -lLLVMSystemZDesc -lLLVMSystemZInfo -lLLVMSystemZAsmPrinter -lLLVMSparcDisassembler -lLLVMSparcCodeGen -lLLVMSparcAsmParser -lLLVMSparcDesc -lLLVMSparcInfo -lLLVMSparcAsmPrinter -lLLVMPowerPCDisassembler -lLLVMPowerPCCodeGen -lLLVMPowerPCAsmParser -lLLVMPowerPCDesc -lLLVMPowerPCInfo -lLLVMPowerPCAsmPrinter -lLLVMNVPTXCodeGen -lLLVMNVPTXDesc -lLLVMNVPTXInfo -lLLVMNVPTXAsmPrinter -lLLVMMSP430CodeGen -lLLVMMSP430Desc -lLLVMMSP430Info -lLLVMMSP430AsmPrinter -lLLVMMipsDisassembler -lLLVMMipsCodeGen -lLLVMMipsAsmParser -lLLVMMipsDesc -lLLVMMipsInfo -lLLVMMipsAsmPrinter -lLLVMLanaiDisassembler -lLLVMLanaiCodeGen -lLLVMLanaiAsmParser -lLLVMLanaiDesc -lLLVMLanaiAsmPrinter -lLLVMLanaiInfo -lLLVMHexagonDisassembler -lLLVMHexagonCodeGen -lLLVMHexagonAsmParser -lLLVMHexagonDesc -lLLVMHexagonInfo -lLLVMBPFDisassembler -lLLVMBPFCodeGen -lLLVMBPFAsmParser -lLLVMBPFDesc -lLLVMBPFInfo -lLLVMBPFAsmPrinter -lLLVMARMDisassembler -lLLVMARMCodeGen -lLLVMARMAsmParser -lLLVMARMDesc -lLLVMARMInfo -lLLVMARMAsmPrinter -lLLVMARMUtils -lLLVMAMDGPUDisassembler -lLLVMAMDGPUCodeGen -lLLVMAMDGPUAsmParser -lLLVMAMDGPUDesc -lLLVMAMDGPUInfo -lLLVMAMDGPUAsmPrinter -lLLVMAMDGPUUtils -lLLVMAArch64Disassembler -lLLVMAArch64CodeGen -lLLVMAArch64AsmParser -lLLVMAArch64Desc -lLLVMAArch64Info -lLLVMAArch64AsmPrinter -lLLVMAArch64Utils -lLLVMObjectYAML -lLLVMLibDriver -lLLVMOption -lLLVMWindowsManifest -lLLVMX86Disassembler -lLLVMX86AsmParser -lLLVMX86CodeGen -lLLVMGlobalISel -lLLVMSelectionDAG -lLLVMAsmPrinter -lLLVMX86Desc -lLLVMMCDisassembler -lLLVMX86Info -lLLVMX86AsmPrinter -lLLVMX86Utils -lLLVMMCJIT -lLLVMLineEditor -lLLVMInterpreter -lLLVMExecutionEngine -lLLVMRuntimeDyld -lLLVMCodeGen -lLLVMTarget -lLLVMCoroutines -lLLVMipo -lLLVMInstrumentation -lLLVMVectorize -lLLVMScalarOpts -lLLVMLinker -lLLVMIRReader -lLLVMAsmParser -lLLVMInstCombine -lLLVMBitWriter -lLLVMAggressiveInstCombine -lLLVMTransformUtils -lLLVMAnalysis -lLLVMProfileData -lLLVMObject -lLLVMMCParser -lLLVMMC -lLLVMDebugInfoCodeView -lLLVMDebugInfoMSF -lLLVMBitReader -lLLVMCore -lLLVMBinaryFormat -lLLVMSupport -lLLVMDemangle -lrt -ldl -lpthread -lm

  g++: error: unrecognized command line option ‘-Wcovered-switch-default’

  g++: error: unrecognized command line option ‘-Wstring-conversion’

  Makefile.linux:20: recipe for target 'libllvmlite.so' failed

  make: *** [libllvmlite.so] Error 1

  7.0.0

  

  SVML not detected

  Traceback (most recent call last):

    File "/tmp/pip-install-pflm3cvt/llvmlite/ffi/build.py", line 192, in <module>

      main()

    File "/tmp/pip-install-pflm3cvt/llvmlite/ffi/build.py", line 182, in main

      main_posix('linux', '.so')

    File "/tmp/pip-install-pflm3cvt/llvmlite/ffi/build.py", line 174, in main_posix

      subprocess.check_call(['make', '-f', makefile])

    File "/opt/python/3.5.6/lib/python3.5/subprocess.py", line 271, in check_call

      raise CalledProcessError(retcode, cmd)

  subprocess.CalledProcessError: Command '['make', '-f', 'Makefile.linux']' returned non-zero exit status 2

  error: command '/home/travis/virtualenv/python3.5.6/bin/python' failed with exit status 1

  

  ----------------------------------------

  Failed building wheel for llvmlite

  Running setup.py clean for llvmlite

Successfully built librosa resampy audioread

Failed to build llvmlite
```

@jtcramer can you help?

**Comment by jtcramer** [comment]
Sorry, finally getting a look at this. It looks like the issue is caused by the PyPI package llvmlite for Python 3.5 no longer being supported, due to Python 3.5 no longer receiving active support from the Python team: https://github.com/numba/llvmlite/issues/471

So perhaps it is wise to just drop support for Python 3.5, since Python 3.5 has already reached EOL.

**Comment by jtcramer** [comment]
Regarding the code fixes, it looks fine to me.

**Comment by jtcramer** [comment]
In response to this it might be a good idea to start supporting Python 3.7 and Python 3.8 (we can probably hold off on 3.9 since it was just released last month)

**Comment by jtcramer** [comment]
This comes from librosa and resampy's dependency on numba, which requires llvmlite: https://github.com/librosa/librosa/issues/1104#issuecomment-636016036

**Comment by lostanlen** [comment]
Noted. Will update the PR to remove py35 and enable py37 and py38

**Comment by lostanlen** [comment]
sounds like you're on it :)
please change the version number to v0.2 (because we're changing dependencies and default model) and then merge at your convenience

**Comment by lostanlen** [comment]
@jtcramer merge?

**Pull request merged**
